#!/bin/bash
set -e

while getopts 't' flag; do
  case "${flag}" in
    t) test_flag=1 ;;
  esac
done

rm -rf ./dist

if [[ -v test_flag ]]; then
  npx prettier --check ./src ./package.json ./tsconfig.json ./webpack.config.js
else
  npx prettier --write ./src ./package.json ./tsconfig.json ./webpack.config.js
fi

npx eslint src
npx webpack
cat ./src/css/* > ./dist/style.css