#!/bin/bash
set -e

while getopts 'b' flag; do
  case "${flag}" in
    b) build_only_flag=1 ;;
  esac
done

# if the build system hasn't been built then build it first, but this will only
# happen once and future updates to the build system need to be manually built
# by running command below
if [ ! -d "./make/dist" ]; then
  (cd make && ./build)
fi

# ensure all the build artefacts exist for each package
node ./make/dist/main.js

# unless run in "build only" mode, start the server
if [[ ! -v build_only_flag ]]; then
  node --env-file=./backend/.env \
    --enable-source-maps \
    ./backend/dist/src/main.js
fi

